spring.application.name=EXTRA_API_Peliculas

spring.datasource.url=jdbc:h2:file:./data/pelis-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# validaciones de JPA...
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=validate

# La primera vez descomentado
# Una vez creada comento
#spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

