
-- -------------------------
-- MOVIES
-- -------------------------
CREATE TABLE movies (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title        VARCHAR(120) NOT NULL,
                        release_year INT          NOT NULL,
                        genre        VARCHAR(30)  NOT NULL,
                        active       BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX uk_movie_title ON movies(title);

-- -------------------------
-- ACTORS
-- -------------------------
CREATE TABLE actors (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        stage_name  VARCHAR(80)  NOT NULL,
                        full_name   VARCHAR(120) NOT NULL,
                        nationality VARCHAR(60),
                        active      BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX uk_actor_stage_name ON actors(stage_name);

-- -------------------------
-- MOVIE_CAST (tabla intermedia N:M con atributos)
-- Un actor NO puede repetir la misma película (PK compuesta)
-- -------------------------
CREATE TABLE movie_cast (
                            movie_id        BIGINT        NOT NULL,
                            actor_id        BIGINT        NOT NULL,
                            character_name  VARCHAR(80)   NOT NULL,
                            screen_minutes  INT           NOT NULL,
                            salary_override DECIMAL(12,2),
                            active          BOOLEAN       NOT NULL,

                            CONSTRAINT pk_movie_cast PRIMARY KEY (movie_id, actor_id),
                            CONSTRAINT fk_mc_movie   FOREIGN KEY (movie_id) REFERENCES movies(id),
                            CONSTRAINT fk_mc_actor   FOREIGN KEY (actor_id) REFERENCES actors(id)
);

CREATE INDEX idx_movie_cast_movie ON movie_cast(movie_id);
CREATE INDEX idx_movie_cast_actor ON movie_cast(actor_id);

-- FASE II
-- -------------------------
-- COUNTRIES (catálogo)
-- -------------------------
CREATE TABLE countries (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           code        VARCHAR(3)   NOT NULL,   -- ISO 3166-1 alpha-3: ESP, USA, FRA...
                           name        VARCHAR(80)  NOT NULL,
                           active      BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX uk_country_code ON countries(code);

-- -------------------------
-- DISTRIBUTORS
-- -------------------------
CREATE TABLE distributors (
                              id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name        VARCHAR(120) NOT NULL,
                              country_id  BIGINT       NOT NULL,
                              active      BOOLEAN      NOT NULL,

                              CONSTRAINT fk_distributor_country FOREIGN KEY (country_id) REFERENCES countries(id)
);

CREATE INDEX idx_distributor_country ON distributors(country_id);

-- -------------------------
-- RELEASES
-- Una película puede estrenarse en varios países por distintas distribuidoras.
-- Una misma película NO puede tener dos estrenos con la misma distribuidora.
-- -------------------------
CREATE TABLE releases (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          movie_id        BIGINT  NOT NULL,
                          distributor_id  BIGINT  NOT NULL,
                          release_date    DATE    NOT NULL,
                          active          BOOLEAN NOT NULL,

                          CONSTRAINT fk_release_movie        FOREIGN KEY (movie_id)       REFERENCES movies(id),
                          CONSTRAINT fk_release_distributor  FOREIGN KEY (distributor_id) REFERENCES distributors(id),
                          CONSTRAINT uk_release_movie_dist   UNIQUE (movie_id, distributor_id)
);

CREATE INDEX idx_release_movie       ON releases(movie_id);
CREATE INDEX idx_release_distributor ON releases(distributor_id);
CREATE INDEX idx_release_date        ON releases(release_date);

-- -------------------------
-- BOX_OFFICE_ENTRIES
-- Registro de recaudación de un estreno en un país durante un periodo.
-- -------------------------
CREATE TABLE box_office_entries (
                                    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    release_id   BIGINT         NOT NULL,
                                    country_id   BIGINT         NOT NULL,
                                    period_start DATE           NOT NULL,
                                    period_end   DATE           NOT NULL,
                                    gross        DECIMAL(14,2)  NOT NULL,   -- recaudación bruta del periodo
                                    screens      INT            NOT NULL,   -- número de pantallas
                                    active       BOOLEAN        NOT NULL,

                                    CONSTRAINT fk_boe_release FOREIGN KEY (release_id) REFERENCES releases(id),
                                    CONSTRAINT fk_boe_country FOREIGN KEY (country_id) REFERENCES countries(id)
);

CREATE INDEX idx_boe_release      ON box_office_entries(release_id);
CREATE INDEX idx_boe_country      ON box_office_entries(country_id);
CREATE INDEX idx_boe_period_start ON box_office_entries(period_start);